# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.IntegerField(primary_key='True', serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('start_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sprinkler',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('duration', models.IntegerField()),
                ('order', models.IntegerField()),
                ('scheduler_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprinkler.Scheduler')),
            ],
        ),
    ]
