# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-12 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprinkler', '0002_auto_20160812_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='start_time',
            field=models.TimeField(verbose_name='%H:%M'),
        ),
    ]
