# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-02 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprinkler', '0004_scheduler_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('humidity', models.FloatField()),
                ('temperature', models.FloatField()),
                ('timestamp', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
